# Jovan Lanik's picom config 1.0
# www.github.com.com/jovanlanik
# clean and simple

backend = "glx";
use-damage = true;
unredir-if-possible = true;
vsync = true;
refresh-rate = 60;

fading = true;
fade-delta = 10; 
fade-in-step = 0.1;
fade-out-step = 0.1;
no-fading-openclose = true;

shadow-exclude = [
	"!(I3_FLOATING_WINDOW@:c || class_g = 'i3-frame')"
];
shadow = true;
shadow-radius = 8;
shadow-opacity = 0.5;
shadow-offset-x = -8;
shadow-offset-y = -4;
shadow-red = 0; #0.047;
shadow-green = 0; #0.047;
shadow-blue = 0; #0.047;

corner-radius = 4;
rounded-corners-exclude = [
	"!(I3_FLOATING_WINDOW@:c || class_g = 'i3-frame')"
];

