#!/bin/sh
if lspci -n | grep -q '1002:67df'
then
	export XORGCONFIG='xorg.external.conf'
fi

if [ -z "$XDG_VTNR" ]; then
	exec /usr/bin/X -nolisten tcp -config $XORGCONFIG "$@"
else
	exec /usr/bin/X -nolisten tcp -config $XORGCONFIG "$@" vt$XDG_VTNR
fi
