Net/ThemeName "Adwaita"
Net/IconThemeName "Adwaita"
Net/SoundThemeName "freedesktop"
Xft/Hinting 1
Xft/HintStyle "hintfull"
Xft/Antialias 1
Xft/RGBA "rgb"
Xft/lcdfilter "lcddefault"
Gtk/MonospaceFontName "Monospace 10"
Gtk/ToolbarStyle "icons"
Gtk/FontName "Sans 10"
Gtk/MenuImages 1
Gtk/ButtonImages 1
Gtk/OverlayScrolling 0
